/**
*****************************************************************************************
*     Copyright(c) 2022, Realtek Semiconductor Corporation. All rights reserved.
*****************************************************************************************
  * @file     asp_svc.h
  * @brief    Head file for using Human Interface Device Service.
  * @details  HIDS data structs and external functions declaration.
  * @author   Leon_liu
  * @date     2022-10-28
  * @version  v1.0
  * *************************************************************************************
  */

#ifndef _ASP_SVC_H_
#define _ASP_SVC_H_

#ifdef  __cplusplus
extern "C" {
#endif      /* __cplusplus */

#if F_APP_GATT_SERVER_EXT_API_SUPPORT

#include "bt_gatt_svc.h"

/** @defgroup ASP_SVC Human Interface Device Service of CFU
  * @brief  Human Interface Device Service
   * @details

    The ASP Service exposes data and associated formatting for ASP Devices and ASP Hosts.

    Application shall register ASP service when initialization through @ref asp_add_service function.

    Application can send report data of ASP service to the client with a notification through @ref asp_send_data function.

  * @{
  */


/*============================================================================*
 *                         Macros
 *============================================================================*/
/** @defgroup ASP_GATT_Exported_Macros ASP Exported Macros
  * @brief
  * @{
  */

/** @defgroup ASP_GATT_Index ASP Attribute Index
  * @brief Index defines for Characteristic's value in HID Device
  * @{
  */
#define GATT_ASP_SVC_9A_VALUE_INDEX (2)
#define GATT_ASP_SVC_9B_VALUE_INDEX (5)
/** @} */

/** End of ASP_GATT_Exported_Macros
* @}
*/


/*============================================================================*
 *                         Types
 *============================================================================*/
/** @defgroup ASP_GATT_Exported_Types asp gatt Exported Types
  * @brief
  * @{
  */
typedef enum
{
    ASP_DATA_9A,
    ASP_DATA_9B,
} T_ASP_DATA_TYPE;

/** @defgroup ASP_GATT_Upstream_Message  Upstream Message
  * @brief  Up message used to inform application.
  * @{
  */
typedef struct
{
    uint16_t                    conn_handle;
    uint16_t                     cid;
    uint16_t                    data_len;
    uint8_t                     *p_data;
} T_ASP_CALLBACK_DATA;

/** @} End of ASP_GATT_Upstream_Message */


/** End of ASP_GATT_Exported_Types
* @}
*/


/*============================================================================*
 *                         Functions
 *============================================================================*/
/** @defgroup ASP_GATT_Exported_Functions ASP gatt Exported Functions
  * @brief
  * @{
  */

/**
  * @brief       Add HID service to the BLE stack database.
  *
  *
  * @param[in]   p_func  Callback when service attribute was read, write or cccd update.
  * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval Others Service id assigned by stack.
  *
  * <b>Example usage</b>
  * \code{.c}
     void profile_init()
     {
         server_init(1);
         asp_id = asp_add_service(app_handle_profile_message);
     }
  * \endcode
  */
T_SERVER_ID asp_add_service(void *p_func);

/**
 * @brief       Send asp notification data .
 *
 *
 * @param[in]   conn_id  Connection handle.
 * @param[in]   data_type data type.
 * @param[in]   p_data report value pointer.
 * @param[in]   data_len length of report data.
 * @return Operation result.
 * @retval true Operation success.
 * @retval false Operation failure.
 *
 * <b>Example usage</b>
 * \code{.c}
    void test(void)
    {
        uint8_t conn_id = 0;
        uint8_t asp_test_data[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09};
        asp_send_data(le_get_conn_handle(conn_id), ASP_DATA_9A, asp_test_data, sizeof(asp_test_data));
    }
 * \endcode
 */
bool asp_send_data(uint8_t conn_handle, T_ASP_DATA_TYPE data_type, uint8_t *p_data,
                   uint16_t data_len);


/** @} End of ASP_GATT_Exported_Functions */

/** @} End of ASP_GATT */

#ifdef  __cplusplus
}
#endif      /*  __cplusplus */

#endif
#endif
