/**
*****************************************************************************************
*     Copyright(c) 2017, Realtek Semiconductor Corporation. All rights reserved.
*****************************************************************************************
  * @file     ias_gatt_svc.h
  * @brief    Head file for using immediate alert service.
  * @details  IAS data structs and external functions declaration developed based on bt_gatt_svc.h.
  * @author
  * @date
  * @version  v1.0
  * *************************************************************************************
  */

/* Define to prevent recursive inclusion */
#ifndef _IAS_GATT_SVC_H_
#define _IAS_GATT_SVC_H_

#ifdef  __cplusplus
extern "C" {
#endif      /* __cplusplus */

/* Add Includes here */
#include "bt_gatt_svc.h"


/** @defgroup IAS_GATT_SVC Immediate Alert GATT Service
  * @brief Immediate alert service
  * @details

    The Immediate Alert Service (IAS) exposes a control point to allow a peer device to cause the device to immediately alert.

    Immediate Alert Service contains an Alert Level characteristic, to which any value other than "No Alert" being written will trigger alarm in the device.

    Immediate Alert Service generally constitutes a profile collectively with other Services, such as Proximity or Find Me etc., which enables immediate alert in device.

    Application shall register Immediate Alert Service when initialization through @ref ias_reg_srv function.

  * @{
  */

/*============================================================================*
 *                         Macros
 *============================================================================*/
/** @defgroup IAS_Exported_Macros IAS Exported Macros
  * @brief
  * @{
  */

/** @defgroup IAS_SVC_CB_MSG
  * @brief IAS server callback messages
  * @{
  */
#define GATT_MSG_IAS_SERVER_WRITE_ALERT_LEVEL    0x00
/** @} End of IAS_SVC_CB_MSG */
/** End of IAS_Exported_Macros
* @}
*/

/*============================================================================*
 *                              Types
 *============================================================================*/

/** @defgroup IAS_Exported_Types IAS Exported Types
  * @brief
  * @{
  */
/**
 * @brief P_FUN_IAS_SERVER_APP_CB IAS Server Callback Function Point Definition Function
 *        pointer used in IAS server module, to send events to specific server module.
 *        The events @ref IAS_SVC_CB_MSG.
 */
typedef T_APP_RESULT(*P_FUN_IAS_SERVER_APP_CB)(uint16_t conn_handle, uint16_t cid, uint8_t type,
                                               void *p_data);

/** @brief IAS server write ind
 *         The message data for GATT_MSG_IAS_SERVER_WRITE_ALERT_LEVEL.
*/
typedef struct
{
    T_SERVER_ID service_id;
    uint8_t alert_level;
} T_IAS_SERVER_WRITE_ALERT_LEVEL;

/** @} End of IAS_Exported_Types */

/*============================================================================*
 *                              Functions
 *============================================================================*/

/** @defgroup IAS_Exported_Functions IAS Exported Functions
  * @brief
  * @{
  */

/**
 * @brief Add immediate alert service to the BLE stack database.
 *
 * @param[in]   app_cb  Callback when service attribute was read, write or cccd update.
 * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
 * @retval 0xFF Operation failure.
 * @retval others Service id assigned by stack.
 *
 * <b>Example usage</b>
 * \code{.c}
    void profile_init(uint16_t mode, uint8_t svc_num)
    {
        gatt_svc_init(mode, svc_num);
        ias_id = ias_reg_srv(app_ias_service_callback);
    }
 * \endcode
 */
T_SERVER_ID ias_reg_srv(P_FUN_IAS_SERVER_APP_CB app_cb);

/** @} End of IAS_Exported_Functions */

/** @} End of IAS_GATT_SVC */


#ifdef  __cplusplus
}
#endif      /*  __cplusplus */

#endif //_IAS_GATT_SVC_H_

