#ifndef _MCP_DEF_INT_H_
#define _MCP_DEF_INT_H_

#ifdef  __cplusplus
extern "C" {
#endif

#include "ots_def.h"
#include "mcp_def.h"

#define MCS_MEDIA_CTRL_POINT_OPCODES_SUP_ATTR_VALUE_LEN       4

#define MCS_UUID_CHAR_MEDIA_PLAYER_ICON_OBJECT_ID                    0x2B94
#define MCS_UUID_CHAR_MEDIA_PLAYER_ICON_URL                          0x2B95
#define MCS_UUID_CHAR_PLAYBACK_SPEED                                 0x2B9A
#define MCS_UUID_CHAR_SEEKING_SPEED                                  0x2B9B
#define MCS_UUID_CHAR_CURRENT_TRACK_SEGMENTS_OBJECT_ID               0x2B9C
#define MCS_UUID_CHAR_CURRENT_TRACK_OBJECT_ID                        0x2B9D
#define MCS_UUID_CHAR_NEXT_TRACK_OBJECT_ID                           0x2B9E
#define MCS_UUID_CHAR_PARENT_GROUP_OBJECT_ID                         0x2B9F
#define MCS_UUID_CHAR_CURRENT_GROUP_OBJECT_ID                        0x2BA0
#define MCS_UUID_CHAR_PLAYING_ORDER                                  0x2BA1
#define MCS_UUID_CHAR_SEARCH_RESULTS_OBJECT_ID                       0x2BA6
#define MCS_UUID_CHAR_SEARCH_CONTROL_POINT                           0x2BA7

#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_PREVIOUS_SEGMENT         0x20
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_NEXT_SEGMENT             0x21
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_FIRST_SEGMENT            0x22
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_LAST_SEGMENT             0x23
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_GOTO_SEGMENT             0x24
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_GOTO_TRACK               0x34
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_PREVIOUS_GROUP           0x40
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_NEXT_GROUP               0x41
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_FIRST_GROUP              0x42
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_LAST_GROUP               0x43
#define MCS_MEDIA_CONTROL_POINT_CHAR_OPCODE_GOTO_GROUP               0x44

#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_PREVIOUS_SEGMENT         0x00000040
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_NEXT_SEGMENT             0x00000080
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_FIRST_SEGMENT            0x00000100
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_LAST_SEGMENT             0x00000200
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_GOTO_SEGMENT             0x00000400
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_GOTO_TRACK               0x00008000
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_PREVIOUS_GROUP           0x00010000
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_NEXT_GROUP               0x00020000
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_FIRST_GROUP              0x00040000
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_LAST_GROUP               0x00080000
#define MCS_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED_CHAR_BIT_VALUE_GOTO_GROUP               0x00100000

//Object Transfer Service object types
#define MEDIA_PLAYER_ICON_OBJ_TYPE                  0x2BA9
#define TRACK_SEGMENGS_OBJ_TYPE                     0x2BAA
#define TRACK_OBJ_TYPE                              0x2BAB
#define GROUP_OBJ_TYPE                              0x2BAC

#define SEARCH_POINT_SUCCESS_CODE     0x01
#define SEARCH_POINT_FAILURE_CODE     0x02

#define MCS_READ_LONG_ERR_CODE        0x80

//Playing Order
typedef enum
{
    MCS_SINGLE_ONCE_ORDER = 0x01,
    MCS_SINGLER_REPEAT_ORDER,
    MCS_IN_ORDER_ONCE_ORDER,
    MCS_IN_ORDER_REPEAT_ORDER,
    MCS_OLDEST_ONCE_ORDER,
    MCS_OLDEST_REPEAT_ORDER,
    MCS_NEWEST_ONCE_ORDER,
    MCS_NEWEST_REPEAT_ORDER,
    MCS_SHUFFLE_ONCE_ORDER,
    MCS_SHUFFLE_REPEAT_ORDER,
    MCS_PLAYING_ORDER_MAX,
} T_PLAYING_ORDER;

//Search control point type
typedef enum
{
    MCS_TACK_NAME_TYPE = 0x01,
    MCS_ARTIST_NAME_TYPE,
    MCS_ALBUM_NAME_TYPE,
    MCS_GROUP_NAME_TYPE,
    MCS_EARLIEST_YEAR_TYPE,
    MCS_LATEST_YEAR_TYPE,
    MCS_GENRE_TYPE,
    MCS_ONLY_TRACKS_TYPE,
    MCS_ONLY_GROUPS_TYPE,
    MCS_SEARCH_TYPE_MAX,
} T_SEARCH_TYPE;

//object type field
typedef enum
{
    MCS_TRACK_OBJ_TYPE        = 0,
    MCS_GROUP_OBJ_TYPE,
    MCS_OBJ_TYPE_RFU
} T_OBJ_TYPE_FLD;

typedef struct
{
    uint8_t   type;
    uint8_t   obj_id[OTS_OBJ_ID_LEN];
} T_MCS_GP_OBJ;

#ifdef  __cplusplus
}
#endif

#endif
