
/* Define to prevent recursive inclusion */
#ifndef _TILE_BLE_SERVICE_H_
#define _TILE_BLE_SERVICE_H_

#ifdef __cplusplus
extern "C"  {
#endif      /* __cplusplus */

/* Add Includes here */
#if F_APP_GATT_SERVER_EXT_API_SUPPORT
#include <profile_server_ext.h>
#else
#include <profile_server.h>
#endif

#define BLE_GAP_ADDR_LEN (6)

#define BLE_CONN_HANDLE_INVALID 0xFFFF  /**< Invalid Connection Handle. */

/** @defgroup APP_TILE_SHIM         APP TILE SHIM
  * @brief
  * @{
  */


/** @defgroup Tile_Service Tile Ble Service
  * @brief Tile BLE service
  * @{
  */
/*============================================================================*
 *                              Macros
 *============================================================================*/

#define TILE_BLE_SERVICE_CHAR_V2_WRITE_INDEX          0x02
#define TILE_BLE_SERVICE_CHAR_V3_NOTIFY_INDEX         0x04
#define TILE_BLE_SERVICE_CHAR_NOTIFY_CCCD_INDEX       0x05


/** @defgroup Tile_Service_Write_Info Tile Service Write Info
  * @brief  Parameter for writing characteristic value.
  * @{
  */
#define TILE_WRITE_V2                                       1

/** @} */

/** @defgroup Tile_Service_Notify_Indicate_Info Tile Service Notify Indicate Info
  * @brief  Parameter for enable or disable notification or indication.
  * @{
  */
#define TILE_NOTIFY_INDICATE_V3_ENABLE     1
#define TILE_NOTIFY_INDICATE_V3_DISABLE    2

/** @} End of Tile_Service_Exported_Macros */
/*============================================================================*
 *                              Types
 *============================================================================*/
/** @defgroup TILE_Service_Exported_Types Tile Service Exported Types
  * @brief
  * @{
  */

/** @defgroup TTILE_WRITE_MSG TTILE_WRITE_MSG
  * @brief Tile BLE service written msg to application.
  * @{
  */
typedef struct
{
    uint8_t opcode; //!< ref:  @ref Tile_Service_Write_Info
    T_WRITE_TYPE write_type;
    uint16_t len;
    uint8_t *p_value;
} TTILE_WRITE_MSG;
/** @} End of TTILE_WRITE_MSG */


/** @defgroup TTILE_UPSTREAM_MSG_DATA TTILE_UPSTREAM_MSG_DATA
  * @brief Tile BLE service callback message content.
  * @{
  */
typedef union
{
    uint8_t notification_indification_index; //!< ref: @ref Tile_Service_Notify_Indicate_Info
    uint8_t read_value_index; //!< ref: @ref Tile_Service_Read_Info
    TTILE_WRITE_MSG write;
} TTILE_UPSTREAM_MSG_DATA;
/** @} End of TTILE_UPSTREAM_MSG_DATA */

/** @defgroup TTILE_CALLBACK_DATA TTILE_CALLBACK_DATA
  * @brief Tile BLE service data to inform application.
  * @{
  */
typedef struct
{
    uint8_t  conn_id;
#if F_APP_GATT_SERVER_EXT_API_SUPPORT
    uint16_t conn_handle;
    uint16_t cid;
#endif

    T_SERVICE_CALLBACK_TYPE msg_type;
    TTILE_UPSTREAM_MSG_DATA msg_data;
} TTILE_CALLBACK_DATA;
/** @} End of TTILE_CALLBACK_DATA */

/** @} End of Tile_Service_Exported_Types */
/*============================================================================*
 *                              Functions
 *============================================================================*/
/** @defgroup Tile_Service_Exported_Functions Tile Service Exported Functions
  * @brief
  * @{
  */

/**
  * @brief Add Tile BLE service to the BLE stack database.
  *
  * @param[in]   p_func  Callback when service attribute was read, write or cccd update.
  * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval others Service id assigned by stack.
  *
  */
T_SERVER_ID tile_ble_service_add_service(void *p_func);



/**
  * @brief send notification of Tile notify characteristic value.
  *
  * @param[in] conn_id           connection id
  * @param[in] service_id        service ID of service.
  * @param[in] p_value           characteristic value to notify
  * @param[in] length            characteristic value length to notify
  * @return notification action result
  * @retval 1 true
  * @retval 0 false
  */
bool tile_ble_service_send_v3_notify(uint8_t conn_id, void *p_value, uint16_t length);

/** @} End of Tile_Service_Exported_Functions */

/** @} End of Tile_Service */

/** @} End of APP_TILE_SHIM */

#ifdef __cplusplus
}
#endif

#endif /* _TILE_BLE_SERVICE_H_ */
